# Generated by Django 5.2.7 on 2025-10-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car_DB',
            fields=[
                ('customer_name', models.CharField(max_length=15)),
                ('car_modelno', models.IntegerField()),
                ('cost_of_car', models.IntegerField()),
                ('manufacture_date', models.DateField()),
                ('VIN_number', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
